### ISSUE TITLE
Revise repository to use date-based tags for repository and image releases

### ISSUE THREAD

**Issue by joeltimothyoh** [startersclan/docker-steamcmd#7]
Based on https://github.com/startersclan/docker-steamcmd/pull/5#issuecomment-935115896

**Comment by leojonathanoh** [comment]
could try and use something like https://github.com/theohbrothers/docker-alpine/blob/20211012.0.0/.github/workflows/ci-master-pr.yml#L1329-L1401

**Comment by joeltimothyoh** [comment]
I'm thinking keep it simple by adding a date tag followed by a push. @leojonathanoh

**Comment by joeltimothyoh** [comment]
I believe the rules for building are already taken care of. This issue was opened just so I can get to working on this change asap. I've got other repos based off the same release workflow so it wouldn't take long to sort this one out.

**Comment by leojonathanoh** [comment]
please give an example of a workflow you have that meets criteria in the link in the OP

**Comment by joeltimothyoh** [comment]
Unfortunately this is under `startersclan` and is strictly OSS with community contribution as the priority unlike many of the other image projects.

**Comment by leojonathanoh** [comment]
i'm working on a generic ci workflow config for both calver and semver that should work across all projects.

**Comment by leojonathanoh** [comment]
Managed to get a generic workflow for semver and calver: https://github.com/theohbrothers/docker-alpine/pull/11
